# SPDX-License-Identifier: GPL-3.0-or-later
"""Tests for the local attack asset generated by ``python scripts/dev.py assets``.

The asset is built from the user's character, which never enters the (public) repository,
so every test here skips when the files are not available (CI stays green without them).
"""

import json
import os
import sys
from pathlib import Path

import bpy
import pytest
from bpy_extras import anim_utils

REPO_ROOT = Path(os.environ.get("ASC_REPO_ROOT", Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(REPO_ROOT / "scripts"))
import make_test_assets as mta  # noqa: E402

ASSET = Path(os.environ.get("ASC_TEST_ASSET", REPO_ROOT / "tests" / "assets" / "local" / "attack_test.blend"))
CHARACTER = os.environ.get("ASC_TEST_CHARACTER")

pytestmark = pytest.mark.skipif(not ASSET.exists(), reason=f"{ASSET.name} not generated (python scripts/dev.py assets)")


@pytest.fixture(scope="module")
def scene():
    bpy.ops.wm.open_mainfile(filepath=str(ASSET), load_ui=False)
    return bpy.context.scene


@pytest.fixture(scope="module")
def rig(scene):
    return bpy.data.objects[scene["asc_asset_rig"]]


@pytest.fixture(scope="module")
def channelbag(rig):
    adt = rig.animation_data
    return anim_utils.action_get_channelbag_for_slot(adt.action, adt.action_slot)


def _bone_of(data_path):
    return data_path.split('"')[1]


def test_metadata(scene):
    assert scene["asc_asset_version"].startswith("5.2")
    assert scene["asc_asset_script_version"] == mta.SCRIPT_VERSION
    assert (scene.frame_start, scene.frame_end) == (mta.FRAME_START, mta.FRAME_END)
    assert {m.frame: m.name for m in scene.timeline_markers} == mta.KEY_POSES


def test_attack_action_assigned_to_rig_slot(rig, channelbag):
    adt = rig.animation_data
    assert adt.action.name == mta.ACTION_NAME
    assert adt.action_slot is not None
    assert adt.action_slot.identifier == "OB" + rig.name
    assert len(adt.action.slots) == 1 and len(adt.action.layers) == 1
    assert channelbag is not None and len(channelbag.fcurves) > 0


def test_expected_controls_keyed(channelbag):
    keyed = {_bone_of(fc.data_path) for fc in channelbag.fcurves}
    assert keyed == set(mta.KEYED_BONES) | set(mta.IK_FK)
    # spatial controls the sculpt tool targets first, plus FK chains
    for bone in ("hand_ik.R", "foot_ik.L", "foot_ik.R", "torso", "root", "upper_arm_ik_target.R",
                 "thigh_ik_target.L", "thigh_ik_target.R", "upper_arm_fk.L", "forearm_fk.L", "chest", "head"):
        assert bone in keyed


def test_key_poses_at_expected_frames(channelbag):
    for fc in channelbag.fcurves:
        frames = [k.co[0] for k in fc.keyframe_points]
        if fc.data_path.endswith('["IK_FK"]'):
            assert frames == [mta.FRAME_START]
        else:
            assert frames == sorted(mta.KEY_POSES), fc.data_path


def test_transform_keys_are_bezier_auto_clamped(channelbag):
    for fc in channelbag.fcurves:
        if fc.data_path.endswith('["IK_FK"]'):
            continue
        for key in fc.keyframe_points:
            assert key.interpolation == "BEZIER"
            assert key.handle_left_type == key.handle_right_type == "AUTO_CLAMPED"


def test_key_values_match_script_literals(channelbag):
    for frame, bones in mta.POSES.items():
        for bone, channels in bones.items():
            for channel, values in channels.items():
                for index, value in enumerate(values):
                    fc = channelbag.fcurves.find(f'pose.bones["{bone}"].{channel}', index=index)
                    assert fc is not None
                    assert fc.evaluate(frame) == pytest.approx(value, abs=1e-5), (frame, bone, channel, index)


def test_left_arm_fk_right_arm_ik(rig, scene):
    scene.frame_set(mta.FRAME_START)
    for bone, value in mta.IK_FK.items():
        assert rig.pose.bones[bone]["IK_FK"] == pytest.approx(value)


def test_animation_drives_the_rig(rig, scene):
    """Behavioral sanity: the sword hand goes up for anticipation and forward/down at impact."""
    def hand(frame):
        scene.frame_set(frame)
        return rig.matrix_world @ rig.pose.bones["hand_ik.R"].head

    idle, anticipation, impact = hand(1), hand(10), hand(18)
    assert anticipation.z > idle.z + 0.5
    assert impact.y < idle.y - 0.7  # the character attacks toward -Y
    assert impact.z < anticipation.z - 0.5


def test_everything_but_the_rig_is_hidden(rig):
    meshes = [ob for ob in bpy.data.objects if ob.type == "MESH"]
    assert meshes
    for ob in bpy.data.objects:
        if ob is rig:
            assert not ob.hide_viewport
        else:
            assert ob.hide_viewport and ob.hide_render, ob.name


def test_previous_actions_preserved_in_copy(scene, rig):
    fingerprints = json.loads(scene["asc_source_action_fingerprints"])
    previous = scene["asc_asset_previous_action"]
    if previous:
        assert previous in fingerprints
    for name, digest in fingerprints.items():
        action = bpy.data.actions[name]
        assert action.use_fake_user
        assert mta.action_fingerprint(action) == digest, name
        assert action is not rig.animation_data.action


@pytest.mark.skipif(not (CHARACTER and Path(CHARACTER).exists()), reason="ASC_TEST_CHARACTER not configured")
def test_original_actions_untouched(scene):
    """The character file still holds the actions exactly as they were when the asset was generated."""
    assert Path(CHARACTER).name == scene["asc_asset_source"]
    fingerprints = json.loads(scene["asc_source_action_fingerprints"])
    with bpy.data.libraries.load(CHARACTER, link=False) as (src, dst):
        names = [name for name in src.actions if name in fingerprints]
        dst.actions = list(names)  # replaced in place by the loaded Action datablocks
    try:
        assert sorted(names) == sorted(fingerprints)
        for name, action in zip(names, dst.actions):  # appended copies keep the request order
            assert mta.action_fingerprint(action) == fingerprints[name], name
    finally:
        for action in dst.actions:
            bpy.data.actions.remove(action)
